services:
  bucketlistdb:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${BUCKETLIST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BUCKETLIST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${BUCKETLIST_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - bucketlistpgdata:/var/lib/postgresql/data
    networks:
      - bucketlist-network

  bucketlist-service:
    image: bucketlist-service
    build:
      context: ./bucketlist-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - bucketlistdb
    environment:
      BUCKETLIST_POSTGRES_USER: ${BUCKETLIST_POSTGRES_USER}
      BUCKETLIST_POSTGRES_PASSWORD: ${BUCKETLIST_POSTGRES_PASSWORD}
      BUCKETLIST_POSTGRES_DB: ${BUCKETLIST_POSTGRES_DB}
    networks:
      - bucketlist-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - bucketlistdb
    networks:
      - bucketlist-network

volumes:
  bucketlistpgdata:

networks:
  bucketlist-network:
    driver: bridge
